import { Injectable } from '@nestjs/common';
import { Cart, CartStatuses, Product } from '../models';
import { InjectRepository } from '@nestjs/typeorm';
import { CartEntity } from '../entities/cart.entity';
import { Repository } from 'typeorm';
import { CartItemEntity } from '../entities/cart-item.entity';

@Injectable()
export class CartService {

  constructor(
    @InjectRepository(CartEntity)
    private readonly cartRepo: Repository<CartEntity>,
    @InjectRepository(CartItemEntity)
    private readonly itemRepo: Repository<CartItemEntity>,
  ) { }


  async getOrCreateCart(userId: string): Promise<CartEntity> {
    let cart = await this.cartRepo.findOne({
      where: { userId, status: CartStatuses.OPEN },
      relations: { items: true, }
    });

    if (!cart) {
      cart = this.cartRepo.create({ userId });
      cart = await this.cartRepo.save(cart);
    }

    return cart;
  }


  async addItem(
    userId: string,
    productId: string,
    count: number,
  ): Promise<CartEntity> {
    const cart = await this.getOrCreateCart(userId);

    const existing = cart.items?.find(
      (i) => i.productId === productId,
    );

    if (existing) {
      existing.count += count;
      await this.itemRepo.save(existing);
    } else {
      const item = this.itemRepo.create({
        productId,
        count,
        cart,
      });
      await this.itemRepo.save(item);
    }

    return this.getOrCreateCart(userId);
  }

  async findByUserId(userId: string): Promise<Cart | null> {
    const cart = await this.cartRepo.findOne({
      where: { userId, status: CartStatuses.OPEN },
      relations: {
        items: true,
      },
    });

    return cart ? this.mapToCartDto(cart) : null;
  }

  async createByUserId(userId: string): Promise<Cart> {
    const cart = this.cartRepo.create({
      // id - is autogenerated column
      userId,
      // createdAt - TypeORM already auto-fills these fields
      // updatedAt - TypeORM already auto-fills these fields
      status: CartStatuses.OPEN,
    });

    const saved = await this.cartRepo.save(cart);

    return this.mapToCartDto(saved);
  }


  async findOrCreateByUserId(userId: string): Promise<Cart> {
    const userCart = await this.findByUserId(userId);

    if (userCart) {
      return userCart;
    }

    return this.createByUserId(userId);
  }


  async updateByUserId(
    userId: string,
    payload: { product: Product; count: number },
  ): Promise<Cart> {
    let cart = await this.cartRepo.findOne({
      where: { userId, status: CartStatuses.OPEN },
      relations: { items: true },
    });

    if (!cart) {
      cart = await this.cartRepo.save(
        this.cartRepo.create({ userId }),
      );
    }

    const existingItem = cart.items?.find(
      (item) => item.productId === payload.product.id,
    );

    if (!existingItem && payload.count > 0) {
      const newItem = this.itemRepo.create({
        productId: payload.product.id,
        count: payload.count,
        cart,
      });

      await this.itemRepo.save(newItem);
    } else if (existingItem && payload.count === 0) {
      await this.itemRepo.remove(existingItem);
    } else if (existingItem) {
      existingItem.count = payload.count;
      await this.itemRepo.save(existingItem);
    }

    const updated = await this.cartRepo.findOne({
      where: { id: cart.id },
      relations: { items: true },
    });

    return this.mapToCartDto(updated!);
  }


  async removeByUserId(userId: string): Promise<void> {
    const cart = await this.cartRepo.findOne({
      where: { userId, status: CartStatuses.OPEN },
    });

    if (!cart) return;

    await this.cartRepo.remove(cart);
  }

  private mapToCartDto(cart: CartEntity): Cart {
    return {
      id: cart.id,
      user_id: cart.userId,
      status: cart.status as CartStatuses,

      created_at: cart.createdAt.getTime(),
      updated_at: cart.updatedAt.getTime(),

      items: (cart.items || []).map((item) => ({
        product: {
          id: item.productId,
        } as Product, // minimal product (as required by task)
        count: item.count,
      })),
    };
  }
}
